arrays solved
vvvvk/study pull request #1
Opened 2020-05-11 15:21 UTC by vvvvk

2020-05-14 20:54 UTC, artempartos commented
нужно поключить проект к travis ci

2020-05-14 20:57 UTC, artempartos requested changes

2020-05-14 20:57 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +      def reduce(array, acc = nil)
собственный reduce в этом задании реализовывать не нужно

2020-05-14 20:57 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        reduce(array, []) { |acc, el| acc << (el.positive? ? max : el) }
здесь логичнее map

2020-05-14 20:57 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +            iter.call(part[0, index], shift_index)
реализация плоха тем, что в рекурсии в этой строке ты создаешь новый массив, не оптимально по памяти, попробуй еще варианты

2020-05-15 18:54 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        iter = lambda { |shift_index, len|
нестандартная реализация на сдвиге индекса и длине, но работать будет

2020-05-15 18:54 UTC, artempartos commented
Правда не вижу результата travis ci

2020-05-15 18:58 UTC, vvvvk commented on test/exercise/arrays/solution.rb
> +        iter = lambda { |shift_index, len|
а стандартная какая?
верхняя и нижняя граница индекса для поиска?

2020-05-15 18:59 UTC, vvvvk commented
> Правда не вижу результата travis ci

теперь есть )

2020-05-15 19:14 UTC, artempartos approved these changes

2020-05-15 19:31 UTC, merged